### ISSUE TITLE
Deletes temp file w/o verifying import

### ISSUE THREAD

**Issue by fsargent** [pxlrbt/move-wsl#1]
I had the unfortunate experience of using this script and it deleted install and temp file. Argh! I think this was because I got Access Denied on the export, but it still went ahead on the full steps. It should check to see that the export was successful before deleting everything.

**Comment by pxlrbt** [comment]
@fsargent I should have known, that this will cause trouble 🙈 Just out of curiosity: Were you using the bash or batch version? Maybe I can improve the scripts a bit next week.

**Comment by pxlrbt** [comment]
@fsargent I added some tests to both scripts which will check export and import file.
