### ISSUE TITLE
Fails with `ERROR: Import failed. Target file not found.` if using WSL1

### ISSUE THREAD

**Issue by jeremyVignelles** [pxlrbt/move-wsl#10]
I tried moving my newly created distribution, and it failed with the message : 

```
ERROR: Import failed. Target file not found.
```

Indeed, I forgot to set the default version, and the distribution was using WSL1.

The script expected a file named "ext4.vhdx", while I had a `rootfs` folder.

Please either check for the existence of either `ext4.vhdx` or the `rootfs` folder, or explain in the message that it might be caused by the distribution being WSL1.

**Comment by pxlrbt** [comment]
@jeremyVignelles Thanks for reporting. Was everything else working fine?

**Comment by jeremyVignelles** [comment]
Yes, I'm currently using my exported distribution that I converted afterwards using `wsl --set-version`, I just needed to set the username as described in the FAQ in the README

**Comment by pxlrbt** [comment]
@Schop0 Do we need this verification at all? Shouldn't checking the registered distro be enough?

**Comment by jeremyVignelles** [comment]
Actually, I'm having issues with the network, but I don't think that's related.
I also think that the registration check should be enough. If it manages to register the distribution, it means that everything went fine IMHO.

**Comment by pxlrbt** [comment]
> I also think that the registration check should be enough. If it manages to register the distribution, it means that everything went fine IMHO.

I just saw that the Batch version is only checking the file path and not the registered version. Did you use the PowerShell version?

**Comment by jeremyVignelles** [comment]
Sorry, I didn't mentionned that.
I tried the bash version in my git-bash, and then tried the PowerShell version, because I assumed that the git-bash path conversion messed everything up once again.

**Comment by pxlrbt** [comment]
This should be resolved with version 1.3.0 now.

**Comment by jeremyVignelles** [comment]
Except for the bash part, isn't it ?

**Comment by pxlrbt** [comment]
Thanks for pointing out. I totally overlooked that the bash version is also checking the files. Should be resolved now.

**Comment by Schop0** [comment]
> @Schop0 [...] Shouldn't checking the registered distro be enough?

Yes, but only if we delete the old distro _after_ that check. Is that possible or will importing the new distro conflict with the old?
If possible, we can delay the deletion and skip the entire temp-file-checking :)

**Comment by pxlrbt** [comment]
@Schop0 At the moment it's just an additional check after checking the import. It shouldn't be needed but it wasn't much work to add the new directory so I kept it.
