### ISSUE TITLE
PLEASE CHECK INPUT BEFORE TAKING ACTION [DANGER ZONE]!!!!

### ISSUE THREAD

**Issue by robokamran** [pxlrbt/move-wsl#13]
dude please check inputs before unregistering WSL! the script unregistered and cleared everything and after that send an error that the target location is incorrect!!!!!!
it deleted my virtual machine along with my codes, installs files etc.!! and now I have no way of turning back :((((( I have to reinstall even the whole WSL! since even wsl is not functioning well :(
the script is really dangerous!

![image](https://user-images.githubusercontent.com/8957516/89708050-1b4d0200-d989-11ea-92f8-13acaf348f3c.png)

**Comment by pxlrbt** [comment]
@robokamran 
Could you provide additional information? Which version did you use (Bash, PS, Batch)? What was the error that occured? The script should check the output of the export.

**Comment by robokamran** [comment]
I have added the screenshot of my windows terminal. It is explanatory. I used the batch version (since windows terminal couldn't run the PS I don't know why)

**Comment by pxlrbt** [comment]
Thanks for the screenshot and sorry for the lost data. Actually the script should check the result of the export and the temporary file. I can reproduce the error but need to check why this isn't working.

**Comment by pxlrbt** [comment]
Still have no idea why the checks for the export failed, but seems like this was also related to the path with spaces. This should be fixed with version 1.3.1.

**Comment by robokamran** [comment]
I also think that the problem is related to the path with spaces, because the script created two folders with the names "Program" and "Files" in my "D" Drive.
