### ISSUE TITLE
Docker Desktop WSL will crash after moving to another Drive

### ISSUE THREAD

**Issue by khasburrahman** [pxlrbt/move-wsl#14]
**Docker Desktop WSL will crash after moving to another Drive**
After I moved docker-desktop and docker-desktop-data to another drive I got errors.

- First, it would crash the current docker and ask for a restart. 
- When I restarted I got this error: 

![image](https://user-images.githubusercontent.com/19620774/90421137-27e8fd00-e0e3-11ea-895e-6c49bb75aacd.png)

What I did: 
- Moved `docker-desktop-data`
- Moved `docker-desktop`
- Then it got an error, and I restarted docker desktop, then the error window popped out

**Script version:**
 - [x] Bash
 - [ ] Powershell
 - [ ] Batch

**Comment by pxlrbt** [comment]
@khasburrahman You didn't stop Docker before moving it's WSL VMs, did you? While moving the WSL will be unregistered and registered again. This will crash docker. I should add this to the readme.
I think your only option is resetting to factory defaults.

**Comment by khasburrahman** [comment]
Correct, I didn't stop docker before moving it. 
Noted, will try to restore docker and try again.

**Comment by crutch12** [comment]
I've fully stopped `docker.exe` and `Docker's services`. But when I used `move-wsl` with `docker-desktop-data` then docker has stopped to start (infinite starting)

**Here is how I fixed it:**

I found out that default docker path for image (`ext4.vhdx` file) is `%USERPROFILE%\AppData\Local\Docker\wsl\data`
_(source: https://stackoverflow.com/a/63752264)_

So you just have to create a symlink to your new target path

```shell
$ mklink /D "%USERPROFILE%\AppData\Local\Docker\wsl\data" "D:\path\to\new\docker-desktop-data"

UPD:
$ mklink /D "%USERPROFILE%\AppData\Local\Docker\wsl" "D:\wsl-data\docker-desktop\wsl"
```

Now everything works fine!

@pxlrbt I think we should update README.md
Or maybe someone could explain why `move-wsl` with `docker-desktop-data` breakes docker (even when it's turned off)

It was really hard to detect how to fix it :)
