### ISSUE TITLE
About the method for changing default user in FAQ

### ISSUE THREAD

**Issue by robokamran** [pxlrbt/move-wsl#15]
**The method presented in readme for changing default user was not possible for me**
I was unable to locate "etc/wsl.conf" in either my PC or my Linux distro.

After a search, I found [this](https://winaero.com/blog/set-default-user-wsl-windows-10) and [this](https://www.tenforums.com/tutorials/128152-set-default-user-windows-subsystem-linux-distro-windows-10-a.html?__cf_chl_jschl_tk__=4df6b3ff321a5c261d9d4e97e3118b726bef19de-1598415262-0-AXI8xmmpevdFlzYkkDWs8Z5Jx3lG2Cz5xljeexk0SBxZAsDI7XR_UWAXbJ1-aM3AtgflL_WvnrFOzxtT4zt5uJUAWFqfgQAEVzbPqjIsnhmUVMGyHPRQbAcXVWl8Uo5oSDntLOygM8VzStgQ9nfZvflDIBuxrWPAOS3EuZjbObcmqaWZSV5MUEEOPgQl15B6SmjsDJ0N2drznb7qzdTtBYcdYXeP-G9E7vtMW6tKstXiDpJFbt1Tv76E4l_YfB0gmhjPMCrFfmWmhABIFDKc31XkBCviEQlq3bQhobCJauab4QGWvT9VqBuw2QGak0scYDsS4F-ytvzFJAqYAKa1h_H7TIysveEPBzIo3JIbcEspRVbJ8NATzdgWu4B514HJSQ) as a working solution.

For example in my PC the command was like this:
`ubuntu1804.exe config --default-user kamran`

Please update the FAQ in the readme to this solution as it is working and standard.

**Comment by pxlrbt** [comment]
> I was unable to locate "etc/wsl.conf" in either my PC or my Linux distro.

If it doesn't exist, you need to create it. Here the option is mentioned in the official docs: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user

It's the safer version as it will persist when moving the distro.

**Comment by pxlrbt** [comment]
I added a bit more information and a link to the Microsoft Docs to the readme.
