### ISSUE TITLE
[Feature Request] Rename the new location

### ISSUE THREAD

**Issue by KoenDG** [pxlrbt/move-wsl#17]
Before discovering this script, I've done some moves manually.

While doing this, I've taken up the system of leaving the base image in place, copying the export and importing it under a different name.

Like _001, _002, etc...

If I screw an image up, that means I can just copy the base image again.

With this script, it just gets moved and if I screw things up, I have to start all over.

**Comment by pxlrbt** [comment]
Although it sounds useful, I don't think this is still in the scope of this script. This would go in the direction of a WSL tools package. At the moment I don't want maintain more functionality for all 3 versions.
