### ISSUE TITLE
WSL 2 distro is imported as WSL 1

### ISSUE THREAD

**Issue by lgodziejewski** [pxlrbt/move-wsl#18]
**Describe the bug**  
First of all - great job on the script, it makes moving distros way easier.

As for the issue - on older Windows versions (< 20150, where WSL 2 is **not** the [default](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20150)), WSL 2 distros are imported as WSL 1. I guess for newer Windows version the same issue happens the other way -> WSL 1 distros are imported as WSL 2.

It's easy to fix it using `wsl --set-version`, however I had a fairly heavy `docker-desktop-data` image which conversion took about 3 hours. I guess it'd be better to import it in the correct version.

According to:
```
    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.
```

it can be set using the `--version` flag (https://github.com/pxlrbt/move-wsl/blob/master/move-wsl#L64). Perhaps the WSL version can be extracted at start when selecting which distro should be moved?

**Script version:**
 - [ x] Bash
 - [ x] Powershell
 - [ x] Batch

**Comment by pxlrbt** [comment]
Thanks for reporting this. I'm aware of this. The distro is always imported as the current default distro. Need to check how much work it is to implement this.
