### ISSUE TITLE
Error - Insufficient system resources exist to complete the requested service.

### ISSUE THREAD

**Issue by xd003** [pxlrbt/move-wsl#19]
**Describe the bug**  
i am just trying to move the ubuntu 20 wsl from my OS drive to a external hard disk , i am getting the error mentioned in question . i am using powershell to do this process . The whole error message is as follows :
```
PS D:\apps\setup\move-wsl-master> ./move-wsl.ps1
Getting distros...
Select distro to move:
1: Ubuntu-20.04
1
Enter WSL target directory:
D:\apps\Ubuntu_20
Move Ubuntu-20.04 to "D:\apps\Ubuntu_20"? (Y|n): y
Exporting VHDX to "D:\apps\Ubuntu_20\Ubuntu-20.04.tar" ...
Insufficient system resources exist to complete the requested service.
D:\apps\setup\move-wsl-master\move-wsl.ps1 : ERROR: Export failed
At line:1 char:1
+ ./move-wsl.ps1
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,move-wsl.ps1

Cleaning up ...
PS D:\apps\setup\move-wsl-master>
```
**Script version:**
 - [x] Powershell - 5.1.19041.1

**Comment by pxlrbt** [comment]
Your external hard drive is "D"? Sounds like you are running out of disk space.

**Comment by xd003** [comment]
> Your external hard drive is "D"? Sounds like you are running out of disk space.

Yes correct the external hard drive is "D"
I think there's some other issue because 
1) it has over 80 gb free 
2)  move command worked well with lxrunoffline 
( Lxrunoffline has created a ext4 extension file in my destination ie D:\apps\Ubuntu_20 )

If there's something else i could help with finding the cause of this issue , do let me know

**Comment by pxlrbt** [comment]
What's the size of that ext4 file? This script is using the native wsl cli by Windows for exporting. LxRunOffline is maybe using a different approach. The exported tar file can get quite large.

**Comment by pxlrbt** [comment]
This could also be related to CPU/Memory. Since the error is coming from the underlying WSL cli there's not really something I can do about. Good that [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline) did work for you.

**Comment by xd003** [comment]
> What's the size of that ext4 file? 

Its size is 1.11 gb

> This could also be related to CPU/Memory

It being a memory or cpu related error makes sense as my secondary machine i tested this on is quite low end. 2 gigs of ram with intel i3

**Comment by pxlrbt** [comment]
> Its size is 1.11 gb

Yeah, that shouldn't be an issue.

> It being a memory or cpu related error makes sense as my secondary machine i tested this on is quite low end. 2 gigs of ram with intel i3

I think it's most likely due to memory. Low cpu should just delay the process.
