### ISSUE TITLE
Import failed. Distro not found.

### ISSUE THREAD

**Issue by ericknyoto** [pxlrbt/move-wsl#20]
Using powershell, I tried to move Distro Ubuntu-20.04 from my HDD (E) to SSD (C).
But the importing was failed with this error message.
```
Enter WSL target directory:
C:\Users\erick\wsl
Move Ubuntu-20.04 to "C:\Users\erick\wsl"? (Y|n): Y
Exporting VHDX to "C:\Users\erick\wsl\Ubuntu-20.04.tar" ...
Unregistering WSL ...
Importing Ubuntu-20.04 from C:\Users\erick\wsl...
Unspecified error
E:\move-wsl.ps1 : Import failed. Distro not found. Export file at C:\Users\erick\wsl\Ubuntu-20.04.tar
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,move-wsl.ps1
```

Then I tried to run again the script. But I couldn't see Ubuntu-20.04 again.
Need help, what happens to all my datas in Distro Ubuntu-20.04?
I can see the files `Ubuntu-20.04.tar` in target directory with size 28GB.

Did I do something wrong?

**Comment by pxlrbt** [comment]
Hm, apparently WSL failed with `Unspecified error`.
You can try registering your WSL manually again with `wsl --import Ubuntu-20.04 C:\Users\erick\wsl C:\Users\erick\wsl\Ubuntu-20.04.tar;` That's the command the script is using under the hood.

**Comment by ericknyoto** [comment]
Thanks!
Looks like my Drive C was run out of storage space. After clean up some space, I ran the command you mention and it all worked as expected.

**Comment by pxlrbt** [comment]
Good that you could resolve this.
