### ISSUE TITLE
The supplied install location is already in use.

### ISSUE THREAD

**Issue by OlafHaalstra** [pxlrbt/move-wsl#24]
**Describe the bug**  
Awesome job on the script! 

The issue is as follows, when you import another distro in the same folder `wsl --import` will fail and report:
```
...
The supplied install location is already in use.
```

This is after the distro is already unregistered. 

**Please add terminal output if possible:**  
```
Move Debian to "C:\..\backup"? (Y|n): y
Exporting VHDX to "C:\..\backup\Debian.tar" ...
Unregistering WSL ...
Importing Debian from C:\..\backup...
The supplied install location is already in use.
```

Makes total sense since there is already an `ext4.vhdx` in the folder, maybe that can be checked before execution?

**Script version:**
 - [ ] Bash
 - [x] Powershell
 - [ ] Batch

**Comment by pxlrbt** [comment]
Thanks for reporting. Yeah there are some other pre-checks that could be added at the moment. I think it would be best to add more support to the PowerShell version. But I am not that proficient in PowerShell scripting, so for now I don't see myself adding these checks.
