### ISSUE TITLE
After moving wsl does not create ext4.vhdx

### ISSUE THREAD

**Issue by akulyk** [pxlrbt/move-wsl#25]
PS K:\docker> ./move-wsl.ps1
Getting distros...
Select distro to move:
1: Ubuntu-18.04
2: docker-desktop-data
3: docker-desktop
2
Enter WSL target directory:
./docker-desktop-data
Move docker-desktop-data to "./docker-desktop-data"? (Y|n): Y
Exporting VHDX to ".\docker-desktop-data\docker-desktop-data.tar" ...
Unregistering WSL ...
Importing docker-desktop-data from ./docker-desktop-data...
Cleaning up ...
Done!
PS K:\docker>

Expect in folder ext4.vhdx
but has two folders rootfs and temp

**Comment by akulyk** [comment]
Solved! The problem was in wsl 1
You should convert into wsl 2 after import

**Comment by pxlrbt** [comment]
Yes, the script isn't aware of the original WSL version of your distro and just imports as the current default version. This was already reported here https://github.com/pxlrbt/move-wsl/issues/18 and is documented in the readme: https://github.com/pxlrbt/move-wsl#wsl-version-was-switched-when-moving-distro
