### ISSUE TITLE
switch to "wsl -l -q" to get distro names

### ISSUE THREAD

**Issue by sidecus** [pxlrbt/move-wsl#5]
This is great and it helped me a lot since I am hitting issues with my system drive.
Thank you for the great work!
I would suggest we switch from ```wsl -l``` to ```wsl -l -q``` to get distro names more safely instead of having to deal with manual string parsing.

BTW I created a PowerShell version. LMK if you are interested and I can send a PR.

Dealing with the wsl output encoding in PowerShell was a bit fun...

**Comment by pxlrbt** [comment]
Thanks for pointing that out. Somehow missed the `-q` option. Makes it a lot easier and is already integrated. 
If you like to share your PowerShell version, I happily accept a PR.

**Comment by sidecus** [comment]
Tried to push to a remote branch, got this:

remote: Permission to pxlrbt/move-wsl.git denied to sidecus.
fatal: unable to access 'https://github.com/pxlrbt/move-wsl.git/': The requested URL returned error: 403

**Comment by pxlrbt** [comment]
@sidecus Did you try to push directly to the repo? You should create a fork, add your changes, go to "Pull Request" > "New pull request" > "Compare across forks". Select your fork as the origin and this repo as the target. 

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by sidecus** [comment]
Got it - thanks for the tips. Just created my own fork an sent the PR.
